### ISSUE TITLE
TLS certificates aren't working since 051f49639d91

### ISSUE THREAD

**Issue by myrup** [AdamBurgess/heroku-buildpack-mono#2]
All my NuGet installs have started failing with "TrustFailure".

```
remote: Building source:
remote: 
remote: -----> Fetching set buildpack https://github.com/AdamBurgess/heroku-buildpack-mono... done
remote: -----> .NET app detected
remote: -----> Installing mono version edaff9f90047-minimal
remote: -----> Downloading https://github.com/AdamBurgess/heroku-buildpack-mono/releases/download/edaff9f90047/mono-minimal.tar.xz
remote: -----> Installing SSL certificates
remote: -----> Installing NuGet packages
remote:        WARNING: Error: TrustFailure
remote:        WARNING: Error: TrustFailure
remote:        WARNING: Error: TrustFailure
remote:        WARNING: Error: TrustFailure
```
As if installing the SSL certificates somehow fail? I've tried clearing the cache as well.

**Comment by AdamBurgess** [comment]
does it happen on every build? or just sporadically? To be honest, I haven't actually deployed something on heroku for months! I'll see if I can get it fixed.

**Comment by myrup** [comment]
Thanks! ;) It happens on every build. I am unable to push any project with NuGet refs.

**Comment by AdamBurgess** [comment]
It's a bit confusing because the way it installs the SSL certs is not some custom step, but actually using the official certificates that Heroku provides for the system.

**Comment by myrup** [comment]
I just pushed an empty project that doesn't use NuGet, but runs:

`new System.Net.WebClient().DownloadData("https://google.com")`

This also dies with TrustFailure. It seems something is broken with mono's certificate store in current versions.

**Comment by AdamBurgess** [comment]
well, darn. Could I ask you to check with an older version of mono, like `mono-4.0.4.1`? I wonder if the way mono reads certificates has changed recently...

**Comment by myrup** [comment]
I pushed MONO_VERSION=96e40c5793ff, which did the trick, but thats a really old version. I think the last time i pushed with a working latest  was about a month ago.

**Comment by myrup** [comment]
FYI: 636c0c95cc78 confirmed working as well

**Comment by AdamBurgess** [comment]
alright
many thanks for reporting this. I should have some time tomorrow to debug. 636c0c95cc78 seems to have been released around a month ago, so I think that's a safe point to lock it to at the moment.

**Comment by myrup** [comment]
Awesome! Thanks for a sweet build pack ;)

**Comment by AdamBurgess** [comment]
This could actually be a mono bug - I asked on mono's gitter and one of the devs said he was seeing the same thing with recent snapshots. A bug was opened at https://bugzilla.xamarin.com/show_bug.cgi?id=39307
It happens somewhere between https://github.com/mono/mono/commit/c9e1f8f2edeb and https://github.com/mono/mono/commit/051f49639d91 where there definitely are changes to SSL.

**Comment by AdamBurgess** [comment]
Hi @myrup, good news!
https://bugzilla.xamarin.com/show_bug.cgi?id=39307 was resolved a few hours ago, and I just compiled a new version and confirmed that HTTPS works fine :)
I'll close this now, but if you're having any problems this can be reopened

**Comment by myrup** [comment]
Thats great @AdamBurgess . Thanks again for the buildpack. Heroku should make it official ;)
