### ISSUE TITLE
Build complete solution, not just the app

### ISSUE THREAD

**Issue by Corstiaan84** [adamburgess/heroku-buildpack-mono#6]
Hi,

When deploying/building a Nancy app, I get the following for all referenced projects in the solution:

`/tmp/build/solution.sln: error : Could not find the project file /tmp/solution/solution.referencedproject/solution.referencedproject.csproj'`

How can I make sure the referenced projects are pushed to dokku as well? They are all in the same repo...

Thanks!

**Comment by adamburgess** [comment]
The buildpack should build all projects associated within the (single) solution in the root folder of the app. Are you sure they're in the repo? I've definitely done builds with multiple projects

**Comment by Corstiaan84** [comment]
I fixed this by fixing all the reference paths in the root .sln file.
