### ISSUE TITLE
"Unable to select a buildpack" when pushing

### ISSUE THREAD

**Issue by Corstiaan84** [adamburgess/heroku-buildpack-mono#7]
When pushing to dokku I get the following message:

`Unable to select a buildpack`

I have set the buildpack url remote like so:

`dokku config:set app_name BUILDPACK_URL=https://github.com/adamburgess/heroku-buildpack-mono.git`

**Comment by adamburgess** [comment]
haven't had much of a play with dokku myself, though sure, I can investigate.

**Comment by Corstiaan84** [comment]
This was due to the fact that my root folder didn't contain a .sln file. Added that and I worked.

**Comment by adamburgess** [comment]
>How to use this

>1. Put a solution in the root directory of your app

;)

**Comment by Corstiaan84** [comment]
:-P
